---
title: "TSA: Forecasting Competition "
author: "Yuxiang Ren and Karen Thornton"
output: pdf_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
---
#packges    
```{r packages}
library(readxl)
#library(xlsx) #this package doesn't work on Macs very well
library(tidyr)
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)

library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)

```

#Data
##temperature
```{r}
#temperature
raw_temperature <- read_excel("Competition/Data/temperature.xlsx")
colnames(raw_temperature) 

##transfer hourly to daily
temperature_day <- raw_temperature %>% 
  group_by(date) %>% 
  summarize(across(starts_with("t_ws"), mean, na.rm = TRUE))
##test result use first day of t_ws1
mean(raw_temperature$t_ws1[c(1:24)])
##save
write.csv(temperature_day, row.names = FALSE, 
          file = "./Competition/Data/temperature_day.csv")
```
## load
```{r}
#load
raw_load <- read_excel("Competition/Data/load.xlsx")
colnames(raw_load) 
## i guess h1 ~h24 mean hours,
## transfer hourly to daily
load_day_long <- raw_load %>%
  pivot_longer(cols = starts_with("h"),
               names_to = "hour",
               values_to = "energy")
load_day <- load_day_long %>% 
  group_by(date) %>% 
  summarize(energy = mean(energy))# use mean

#changed to mean 

##test
sum(load_day_long$energy[1:24])

##save
write.csv(load_day, row.names = FALSE, 
          file = "./Competition/Data/load_day.csv")
```

##humidity
```{r}
#humidity
raw_humidity <- read_excel("Competition/Data/relative_humidity.xlsx")
colnames(raw_humidity) 
##transfer hourly to daily
humidity_day <- raw_humidity %>% 
  group_by(date) %>% 
  summarize(across(starts_with("rh_ws"), mean, na.rm = TRUE))
##test result use first day of t_ws1
mean(raw_humidity$rh_ws1[c(1:24)])
##save
write.csv(humidity_day, row.names = FALSE, 
          file = "./Competition/Data/humidity_day.csv")
```

##final data
**to save space i save the result data, you can only run after this chunk to load data. or we can add "#" before these r chunk**
```{r}
load_day <- read.csv("./Competition/Data/load_day.csv")
temperature_day <- read.csv("./Competition/Data/temperature_day.csv")
humidity_day <- read.csv("./Competition/Data/humidity_day.csv")

```

#create a time series
```{r}
ts_load_daily <- msts(load_day$energy, 
                           seasonal.periods =c(7,365.25),
                           start=c(2005,1,1))
```

#Test_Karen
#create an arima
```{r}
#arima with only one factor
Simple_ARIMA <- auto.arima(ts_load_daily, seasonal=FALSE)
print(Simple_ARIMA)

#simple arima forecast
Simple_ARIMA_for <- forecast(object = Simple_ARIMA, h=365)

#plot
autoplot(ts_load_daily) +
    autolayer(Simple_ARIMA_for,series="ARIMA",PI=FALSE) +
    ylab("Load") +
    xlab("")

#save
write.csv(Simple_ARIMA_for, row.names = FALSE, 
          file = "./Competition/Data/Simple.ARIMA.Forecast.mean.csv")
```

#Test_Karen_2
#Neural Network
```{r}
NN_fit <- nnetar(ts_load_daily,p=1,P=0,xreg=fourier(ts_load_daily, K=c(2,12)))

NN_for <- forecast(NN_fit, h=59,xreg=fourier(ts_load_daily, 
                                          K=c(2,12),h=59))

#plot
autoplot(ts_load_daily) +
  autolayer(NN_for, series="Neural Network",PI=FALSE)+
  ylab("Load") 

#save
write.csv(NN_for, row.names = FALSE, 
          file = "./Competition/Data/Neural.Network.Forecast.csv")
```

#Test_Karen_3
#Neural Network 2
```{r}
NN_fit_2 <- nnetar(ts_load_daily,p=1,P=0,xreg=fourier(ts_load_daily, K=c(2,7)))

NN_for_2 <- forecast(NN_fit_2, h=59,xreg=fourier(ts_load_daily, 
                                          K=c(2,7),h=59))

#plot
autoplot(ts_load_daily) +
  autolayer(NN_for_2, series="Neural Network 2",PI=FALSE)+
  ylab("Load") 

#save
write.csv(NN_for_2, row.names = FALSE, 
          file = "./Competition/Data/Neural.Network.Forecast.2.csv")
```

#Test_Yuxiang


#Result_Model
##1
```{r}

```

##2
